# Generated by Django 5.0.14 on 2026-02-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeCustomerId',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeSubscriptionId',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
