# Generated by Django 5.0.14 on 2026-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_stripecustomer_stripecustomerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
